Add venv creation to deploy action

diff --git a/.github/actions/deploy/action.yml b/.github/actions/deploy/action.yml
--- a/.github/actions/deploy/action.yml
+++ b/.github/actions/deploy/action.yml
@@ -19,10 +19,17 @@ runs:
         repository: mtararujs/python-greetings
         path: python-greetings
 
+    - name: Create virtual environment and install dependencies
+      shell: cmd
+      working-directory: python-greetings
+      run: |
+        python -m venv venv
+        venv\Scripts\python -m pip install -r requirements.txt
+
     - name: Stop existing service if running
       shell: cmd
       working-directory: python-greetings
-      run: pm2 delete greetings-app-${{ inputs.environment }} & EXIT /B 0
+      run: pm2 delete greetings-app-${{ inputs.environment }} || echo "Service not found, continuing..."
 
     - name: Start service with pm2
       shell: cmd
